### ISSUE TITLE
Add 'Default donation amount' option to settings

### ISSUE THREAD

**Issue by julia-smith** [INN/news-match-donation-shortcode#15]
<img width="405" alt="screen shot 2017-10-18 at 12 31 36 pm" src="https://user-images.githubusercontent.com/1643734/31733131-5ad9e098-b400-11e7-896d-3d4fbbaea097.png">

To be used here: https://github.com/INN/news-match-donation-shortcode/blob/abstract-donor-levels/classes/class-newsmatchdonation-shortcode.php#L127

**Comment by benlk** [comment]
What would be really cool for the donation form is having it auto-generate a dropdown of minimum amounts for each level: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Offering_suggested_values

But that's a nice-to-have.
