### ISSUE TITLE
Update plugin description on plugins.php page

### ISSUE THREAD

**Issue by julia-smith** [INN/news-match-donation-shortcode#27]
Currently says:
> Provides methods to integrate with the donation application hosted at checkout.voiceofsandiego.org
<img width="969" alt="screen shot 2017-10-30 at 9 34 51 am" src="https://user-images.githubusercontent.com/1643734/32176430-9e82d8f0-bd55-11e7-8a5f-ffdcbe0fd8de.png">

Please update to say:
> Creates a minimal donation form for FundJournalism.org and NewsMatch.org

**Comment by benlk** [comment]
This is drawn from the plugin file, so to update how this text displays, we're going to have to push an update to wordpress.org. is there anything else we want to fix with this new version of the plugin?
