### ISSUE TITLE
Docs for default styles

### ISSUE THREAD

**Issue by benlk** [INN/news-match-donation-shortcode#4]
We need recommendations for how to style this, including:

- [x] default selectors
- [x] recommended default styles, or examples

**Comment by benlk** [comment]
Since container queries aren't a thing yet, and we want to make the form responsive, can we handle responsiveness using CSS Grid?

There's a situation where the default layout collapses down where it would be nice to rearrange the layout based on the width of the column:

<img width="853" alt="screen shot 2017-09-21 at 8 38 56 pm" src="https://user-images.githubusercontent.com/1754187/30724616-0a6efd58-9f0d-11e7-9116-cc490e3d5aff.png">
<img width="439" alt="screen shot 2017-09-21 at 8 39 14 pm" src="https://user-images.githubusercontent.com/1754187/30724617-0a6fcd00-9f0d-11e7-92a1-647525fc908b.png">

If we're willing to use `@supports` in a media query (supported by [everything except IE 11-](https://caniuse.com/#feat=css-featurequeries), we can have low-shininess full-width styles by default, like we see on Rivard's donation form, which would stretch all the way across the container:
<img width="534" alt="screen shot 2017-09-21 at 8 42 52 pm" src="https://user-images.githubusercontent.com/1754187/30724671-7dd32896-9f0d-11e7-852c-d68ac45eafa0.png">

And then use Grid for more complex layouts in other things.

**Comment by julia-smith** [comment]
Sure, if you want to give that a try – go for it. 

Remember that the `type="select"` option is there to help solve the narrow-column problem, too.

**Comment by benlk** [comment]
Punting on the grid for now; style guidance is in readme.txt and linked to from the settings page.
